### ISSUE TITLE
jq: error (at <stdin>:0): Cannot index string with string "dns_names"

### ISSUE THREAD

**Issue by 0xShin** [nahamsec/lazyrecon#33]
Hi, will you please help me I am getting a error saying this
jq: error (at <stdin>:0): Cannot index string with string "dns_names"

**Comment by 0xShin** [comment]
I don't know why but when running the script the error  is there but by doing it manually the error did not show up.

**Comment by 0xShin** [comment]
Fix:
i added a domain suffix when running the script 
example
./lazyrecon.sh -d site.com

**Comment by velocity16902** [comment]
Fixed for me: 
pip install jq
pip3 install jq
